version: '3'
services:
  db:
    image: postgres:10.5
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: >
      bash -c "mix deps.get --include-children
      && mix deps.compile
      && mix ecto.create 
      && mix ecto.migrate 
      && mix phx.server"
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
    db-data: